"""Add parent_name column to student_forms

Revision ID: 08a7de776569
Revises: f549643efe3b
Create Date: 2025-05-08 10:00:58.702894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a7de776569'
down_revision = 'f549643efe3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_forms', schema=None) as batch_op:
        batch_op.drop_column('achievement_file')

    # ### end Alembic commands ###
