"""Add status column to student_forms

Revision ID: 182071f05038
Revises: 08a7de776569
Create Date: 2025-05-08 10:16:05.901286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182071f05038'
down_revision = '08a7de776569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_forms', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
