"""Tambah kolom payment_proof di StudentForm

Revision ID: 760f0b51806f
Revises: d2e153482b18
Create Date: 2025-05-15 13:06:20.769014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760f0b51806f'
down_revision = 'd2e153482b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_proof', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_forms', schema=None) as batch_op:
        batch_op.drop_column('payment_proof')

    # ### end Alembic commands ###
