"""Update models with relationships

Revision ID: cb72ee6059e9
Revises: eb38104a2a3e
Create Date: 2025-05-17 10:37:12.042350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb72ee6059e9'
down_revision = 'eb38104a2a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accepted_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptance_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('parent_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('previous_school',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_column('achievement_file')
        batch_op.drop_column('address')
        batch_op.drop_column('achievements')
        batch_op.drop_column('accepted_date')

    with op.batch_alter_table('rejected_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejection_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('parent_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('previous_school',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_column('rejected_date')
        batch_op.drop_column('address')
        batch_op.drop_column('achievements')
        batch_op.drop_column('achievement_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rejected_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievement_file', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('achievements', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('rejected_date', sa.DATETIME(), nullable=True))
        batch_op.alter_column('previous_school',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('parent_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('rejection_date')

    with op.batch_alter_table('accepted_students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('achievements', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('achievement_file', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('previous_school',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('parent_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('acceptance_date')

    # ### end Alembic commands ###
