"""Add payment_status column to StudentForm

Revision ID: d2e153482b18
Revises: 
Create Date: 2025-05-15 10:09:36.844818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e153482b18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('parent_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('previous_school',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('achievement_file',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_column('email')
        batch_op.drop_column('achievements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('achievements', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('achievement_file',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('previous_school',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('parent_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
