"""Add notifications and has_submitted_form columns

Revision ID: eb38104a2a3e
Revises: 760f0b51806f
Create Date: 2025-05-17 10:17:28.158261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb38104a2a3e'
down_revision = '760f0b51806f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('has_submitted_form', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_submitted_form')
        batch_op.drop_column('notifications')

    # ### end Alembic commands ###
