"""Update StudentForm model

Revision ID: f549643efe3b
Revises: 
Create Date: 2025-05-08 09:45:56.346259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f549643efe3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('achievements', sa.Text(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('achievements')
        batch_op.drop_column('parent_name')

    # ### end Alembic commands ###
